version: "3.8"

services:
  sql-server-db:
    container_name : mysql-server-db
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD : "Expect_studio@2020"
      MYSQL_DATABASE : "SchoolARDB"